### ISSUE TITLE
Add immutable cache-control extension

### ISSUE THREAD

**Issue by wsargent** [playframework/cachecontrol#18]
Mozilla has a cache-control: immutable extension that can be used here:

https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/

**Comment by dwijnand** [comment]
I assume this idea fell by the wayside.

**Comment by wsargent** [comment]
@dwijnand it did indeed.

**Comment by mkurz** [comment]
Not sure if that relates to here but Play adds `immutable` to the served assets in prod mode:

https://github.com/playframework/playframework/blob/dd271b39cdc5418255cecc4876a6c48b10fdfc00/core/play/src/main/scala/play/api/controllers/Assets.scala#L163
