### ISSUE TITLE
Publish for Scala 3

### ISSUE THREAD

**Issue by SethTisue** [playframework/cachecontrol#182]
should be possible now after #180 and #181

* [x] merge outstanding PRs
* [x] choose version number: 2.1.0
  * there aren't any code changes, but we upgraded to scala-parser-combinators 2.0.0 (from 1.x) and added Scala 3 support, so I think that merits going to 2.1.0 and not just 2.0.1
* [x] tag it
  * https://github.com/playframework/cachecontrol/releases/tag/2.1.0
* [x] wait for release job
  * https://travis-ci.com/github/playframework/cachecontrol/builds/234395399
* [x] wait for artifacts to hit Maven Central
  * https://repo1.maven.org/maven2/com/typesafe/play/cachecontrol_3/
  * (not a complete list)

**Comment by SethTisue** [comment]
@octonato does 2.1.0 seem like a reasonable choice of version number to you? perhaps playframework/* has traditions around this that I'm not familiar with

any other considerations?

**Comment by octonato** [comment]
@SethTisue, the rule is to pick a major version if there is any backward incompatible change. 

But we don't need to be that strict. We can go for 2.1.0 simply because of parser-combinator 2.0 and Scala 3. That said, fine to me if we bump to 2.1.0. 

pinging @marcospereira for a second opinion.

**Comment by marcospereira** [comment]
> That said, fine to me if we bump to 2.1.0.

+1 for that. :-)
